// Repository-wide lesson validation.
// Run from any directory: node tools/validate-lessons.mjs
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outputRoot = path.join(projectRoot, "outputs");
const lessonsRoot = path.join(outputRoot, "lessons");
const appPath = path.join(outputRoot, "app.jsx");
const voiceScriptsPath = path.join(outputRoot, "audio", "voice-scripts.json");
const norm = (value) => String(value || "").trim().toLowerCase()
  .replace(/[‘’]/g, "'")
  .replace(/\s+/g, " ");

const lessonFiles = walk(lessonsRoot)
  .filter((file) => /[/\\](a0|a1|a2|b1|b2)[/\\][^_][^/\\]*\.html$/i.test(file))
  .sort();
const voiceScripts = fs.existsSync(voiceScriptsPath)
  ? JSON.parse(fs.readFileSync(voiceScriptsPath, "utf8"))
  : {};
const readySource = fs.existsSync(appPath) ? fs.readFileSync(appPath, "utf8") : "";
const readyPaths = new Set(
  [...readySource.matchAll(/"(lessons\/(?:a0|a1|a2|b1|b2)\/[^"\n]+\.html)"/g)]
    .map((match) => match[1]),
);

let errorCount = 0;
let warningCount = 0;
let redirectCount = 0;
const publishedLessons = [];

for (const file of lessonFiles) {
  const relative = slash(path.relative(outputRoot, file));
  const html = fs.readFileSync(file, "utf8");
  const errors = [];
  const warnings = [];
  const isRedirect = /<meta\s+http-equiv="refresh"/i.test(html);

  validateDocument(html, file, errors, warnings, isRedirect);
  validateReferences(html, file, errors);
  if (!isRedirect) {
    publishedLessons.push(relative);
    validateLessonContract(html, errors, warnings);
    validateDrills(html, errors);
    validateAudio(html, errors);
    if (!readyPaths.has(relative)) warnings.push("lesson exists but is not listed in READY_LESSONS");
  } else {
    redirectCount += 1;
  }

  errorCount += errors.length;
  warningCount += warnings.length;
  const status = errors.length ? "FAIL" : warnings.length ? "WARN" : "ok  ";
  console.log(`${status} ${relative}`);
  errors.forEach((message) => console.log(`     error: ${message}`));
  warnings.forEach((message) => console.log(`     note:  ${message}`));
}

for (const readyPath of readyPaths) {
  if (!fs.existsSync(path.join(outputRoot, readyPath))) {
    errorCount += 1;
    console.log(`FAIL ${readyPath}`);
    console.log("     error: READY_LESSONS points to a missing file");
  }
}

console.log(
  `\nValidated ${publishedLessons.length} lessons and ${redirectCount} redirect alias` +
  `${redirectCount === 1 ? "" : "es"}: ${errorCount} error${errorCount === 1 ? "" : "s"}, ` +
  `${warningCount} migration note${warningCount === 1 ? "" : "s"}.`,
);
process.exitCode = errorCount ? 1 : 0;

function validateDocument(html, file, errors, warnings, isRedirect) {
  if (!/^<!doctype html>/i.test(html.trim())) errors.push("missing HTML doctype");
  if (!/<html\b[^>]*\blang="[^"]+"/i.test(html)) errors.push("html element is missing lang");
  if (!/<title>[^<]+<\/title>/i.test(html)) errors.push("missing document title");

  const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map((match) => match[1]);
  const duplicates = [...new Set(ids.filter((id, index) => ids.indexOf(id) !== index))];
  if (duplicates.length) errors.push(`duplicate id${duplicates.length === 1 ? "" : "s"}: ${duplicates.join(", ")}`);

  if (!isRedirect && !/<meta\b[^>]*name="description"/i.test(html)) {
    warnings.push("missing meta description (to be generated by the new page template)");
  }

  const images = [...html.matchAll(/<img\b[^>]*>/gi)].map((match) => match[0]);
  const withoutDimensions = images.filter((tag) => !/\bwidth="\d+"/i.test(tag) || !/\bheight="\d+"/i.test(tag));
  if (withoutDimensions.length) warnings.push(`${withoutDimensions.length} image${withoutDimensions.length === 1 ? "" : "s"} missing explicit width/height`);

  const inlineStyle = (html.match(/<style>[\s\S]*?<\/style>/i) || [""])[0];
  if (!isRedirect && inlineStyle.length > 200) warnings.push(`large inline style block (${inlineStyle.length} bytes)`);
}

function validateLessonContract(html, errors, warnings) {
  if (!html.includes("lesson.css")) errors.push("missing shared lesson.css");
  if (!html.includes("drills.css")) errors.push("missing shared drills.css");
  if (!html.includes("lesson.js")) errors.push("missing shared lesson.js");
  if (!/<h1\b[^>]*>[\s\S]*?<\/h1>/i.test(html)) errors.push("missing visible h1");
  if (!/data-quiz\b/.test(html)) errors.push("missing final interactive quiz");
  if (!/Use it in real life|Communicate|Speak[^<]{0,20}make it real/i.test(html)) errors.push("missing student production section");
  if (!/Reflect/i.test(html)) warnings.push("missing explicit reflection section");
  if (!/class="lessons-nav"/.test(html)) warnings.push("missing previous/next lesson navigation");
}

function validateDrills(html, errors) {
  const quizStarts = [...html.matchAll(/<[^>]*data-quiz-item[^>]*>/g)];
  quizStarts.forEach((match, index) => {
    const end = quizStarts[index + 1]?.index ?? html.indexOf("</div></div>", match.index);
    const block = html.slice(match.index, end > match.index ? end : match.index + 4000);
    const answer = match[0].match(/data-answer="([^"]+)"/i)?.[1];
    if (!answer) return errors.push("quiz item missing data-answer");
    const options = [...block.matchAll(/data-quiz-option="([^"]+)"/g)].map((option) => norm(option[1]));
    if (!options.length) errors.push(`quiz answer "${answer}" has no options`);
    else if (!options.includes(norm(answer))) errors.push(`quiz answer "${answer}" is not among its options`);
  });

  for (const match of html.matchAll(/<div\s+class="practice"\s+data-choice-gap-drill[\s\S]*?<div\s+class="drill-actions">/g)) {
    const bank = [...match[0].matchAll(/data-choice-option="([^"]+)"/g)].map((option) => norm(option[1]));
    const answers = [...match[0].matchAll(/data-choice-gap\b[^>]*data-answer="([^"]+)"/g)]
      .flatMap((gap) => gap[1].split("|").map(norm));
    answers.forEach((answer) => {
      if (bank.length && !bank.includes(answer)) errors.push(`choice-gap answer "${answer}" is not in its bank`);
    });
  }

  for (const match of html.matchAll(/data-tile-builder\s+data-answer="([^"]+)"[\s\S]*?data-build-area/g)) {
    const tiles = [...match[0].matchAll(/data-build-tile="([^"]+)"/g)].map((tile) => norm(tile[1]));
    const expected = norm(match[1]).split(" ").sort().join(" ");
    const available = tiles.flatMap((tile) => tile.split(" ")).sort().join(" ");
    if (expected !== available) errors.push(`sentence builder "${match[1]}" does not match its tiles`);
  }

  for (const match of html.matchAll(/data-spot-error\s+data-answer="([^"]+)"[\s\S]*?data-error-feedback/g)) {
    const choices = [...match[0].matchAll(/data-error-choice="([^"]+)"/g)].map((choice) => norm(choice[1]));
    if (!choices.includes(norm(match[1]))) errors.push(`error-spotting answer "${match[1]}" is not among its choices`);
  }
}

function validateAudio(html, errors) {
  for (const match of html.matchAll(/data-voice-clip="([^"]+)"/g)) {
    if (!voiceScripts[match[1]]) errors.push(`unknown voice clip "${match[1]}"`);
  }
}

function validateReferences(html, file, errors) {
  for (const match of html.matchAll(/\b(?:href|src)="([^"]+)"/g)) {
    const reference = match[1];
    if (!reference || /^(?:https?:|mailto:|tel:|data:|#|javascript:)/i.test(reference)) continue;
    const clean = decodeURIComponent(reference.split("#")[0].split("?")[0]);
    if (!clean) continue;
    const target = clean.startsWith("/")
      ? path.join(outputRoot, clean.replace(/^\/+/, ""))
      : path.resolve(path.dirname(file), clean);
    if (!fs.existsSync(target)) errors.push(`broken local reference "${reference}"`);
  }
}

function walk(directory) {
  if (!fs.existsSync(directory)) return [];
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const target = path.join(directory, entry.name);
    return entry.isDirectory() ? walk(target) : target;
  });
}

function slash(value) {
  return value.split(path.sep).join("/");
}
